#!/usr/bin/env sh

# OpenThesaurus API URL
API_URL='https://www.openthesaurus.de/synonyme/search?format=application/json'
# display N_MAX synonyms max.
N_MAX=20

# allow argument or piped data as input
if [ -z "$1" ]; then
        read q
else
        q=$1
fi

# fetch result and make it pretty
curl -s --data-urlencode "q=$q" "$API_URL" \
| jq '. | .synsets[].terms[].term' \
| head -n $N_MAX \
| tr -d '"'
